---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(scales)
library(gridExtra)

```

# R 데이터 분석 문제

### 1. 문장 개선

```{r vec1}
vec1 <- c(1,2,3,4,5,6)
vec2 <- c(10, 9, 8, 7, 6, 5)
vec3 <- c(1,1,2,2,3,3)
vec4 <- c(1,2,3,1,2,3)
vec5 <- c(1,3,5,7,9,11)

vec1_ <- c(1:6)
vec2_ <- c(10:5)
vec3_ <- rep(1:3, each=2)
vec4_ <- rep(c(1:3), 2)
vec5_ <- seq(1, 11, by=2)


print_diff <- rbind(vec1, vec1_, vec2, vec2_, vec3, vec3_, vec4, vec4_, vec5, vec5_)

print(print_diff)
```


### 2. 

#### 2-1.
```{r df_score}
df_score <- data.frame(col1=c(90, 78, 94, 70), col2=c(50, 60, 90, 92))
colnames(df_score) <- c('중간', '기말')
rownames(df_score) <- c('강경학', '김태균', '이성열', '정은원')

#class(df_score)
print(df_score)
```

#### 2-2.
```{r df_score2}
df_score2 <- df_score %>% 
  mutate(평균 = (중간 + 기말) / 2)

df_score2
```



### 3 

```{r }
```


### 4. 

```{r}
oddSum <- function(num) {
  sum <- 0
  i <- 1
  
  for(i in seq(1, num, by=2)) {
    sum <- sum + i
  }
 
  return(sum)
}

print(oddSum(100))
```


### 5. 

#### 5-1.
```{r }
ir_set <- iris %>%
  filter(Species == 'setosa')

boxplot(ir_set$Sepal.Width)
```

#### 5-2.


### 6. 

```{r }

mpg %>%
  filter(manufacturer=='toyota') %>%
  group_by(model) %>%
  mutate(ch_avg = (cty + hwy)/2) %>% 
  summarise(average = mean(ch_avg)) %>%
  arrange(desc(average)) %>%
  head(3)

```


### 7. 

#### 7-1.
```{r }
cty_suv <- mpg %>%
  filter(class=='suv') %>%
  group_by(manufacturer) %>%
  summarise(시내연비 = mean(hwy)) %>%
  arrange(desc(시내연비)) %>%
  head(7)
cty_suv
```

#### 7-2.
```{r }
ggplot(cty_suv, aes(x=manufacturer, y=시내연비, fill=manufacturer)) + 
  geom_bar(stat='identity') +
  theme(legend.position = 'none')
```

### 8. 


### 9. 

```{r }
data <- read.csv('../data/야구성적.csv', header=T)

df_data <- data %>%
  mutate(OPS= 출루율+장타율)  %>%
  mutate(연봉대비OPS = OPS/연봉 * 100) %>% 
  select(선수명, OPS, 연봉대비OPS)

ggplot(data=df_data, aes(x=선수명, y=연봉대비OPS, fill=선수명)) +
  geom_text(aes(label=sprintf("%0.2f%%", 연봉대비OPS)), vjust=0) +
  geom_bar(stat='identity') +
  theme(legend.position = 'none')

```


