---
title: "0611_wordcloud_과제"
date: '2019-06-11'
author: "임도균"
output: html_document
---

### 2019-06-11 word cloud 과제
#### 서울시 응답소 2015년 데이터에서 키워드를 찾아 word cloud를 만든다
#### 조건은 다음과 같다.
1. 제거할 단어를 저장한 gsub 파일을 만든다.
2. stringr 패키지를 사용한다.
3. R Markdown으로 보고서를 제작, 제출한다.



### 1. R Set Up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rJava)
library(KoNLP)
library(wordcloud)
library(stringr)
library(RColorBrewer)
useSejongDic()
```

### 2. 데이터 입력

```{r datas}
# getwd()
datas <- readLines('../data/서울시 응답소_2015년전체/응답소_2015_01.txt')
i <- 1
for(i in 2:12) {
  datas <- c(datas, readLines(sprintf('../data/서울시 응답소_2015년전체/응답소_2015_%02d.txt', i)))
}
```

### 데이터 처리

```{r rev, echo=FALSE}
words <- sapply(datas, extractNoun, USE.NAMES = F)
data <- unlist(words)

gsub_txt <- readLines('../data/gsub_data.txt')
i <- 1
for(i in 1:length(gsub_txt)) {
  data <- gsub((gsub_txt[i]), '', data)
}

data <- str_replace_all(data, '[^[:alpha:]]', '') # 한영 제외 삭제, stringr library 사용
data <- Filter(function(x) {nchar(x) >=2}, data)
data <- gsub(' ', '', data)
data <- gsub('"\n', '', data)

write(unlist(data), '../data/seoul_2.txt') # remove space/crlf
rev <- read.table('../data/seoul_2.txt')
nrow(rev) #126933
```


### 데이터 표현

```{r wordcount, echo=FALSE}
wordcount <- table(rev)
head(sort(wordcount, decreasing = T), 30)

palete <- brewer.pal(9, 'Set1')
wordcloud(names(wordcount), freq=wordcount, scale=c(5,1), rot.per=0.25, min.freq=100,
          random.order = F, random.color = T, colors = palete)
legend(0.3, 1, '서울시 응답소 2015년 분석자료', cex=0.8, fill=NA, border=NA, bg='white',
       text.col='red', text.font=2, box.col='red')

```

